---
title: "**Revelado de Arquitecturas**"
--- 
<br>
<br>
<br>

<div class=text-justify>

# **Arquitectura de datos**

<br>


### Definición de Arquitectura de información (MOE de la DGIAI)

Se refiere a la definición del esquema de los componentes (actores, modelos de datos, estándares, sistemas tecnológicos), y sus interrelaciones, que conforman la estructura que soporta los procesos de producción de información estadística y geográfica. 


### [Plan de Arquitectura](https://365inegi-my.sharepoint.com/:w:/r/personal/raul_mejia_inegi_org_mx/_layouts/15/Doc.aspx?sourcedoc=%7B23E2A8D9-50BF-4DB3-AE41-44363191F80D%7D&file=Plan%20de%20Arquitectura%20de%20Datos.docx&action=default&mobileredirect=true){target="_blank"}
<br>
<br>


# **Marcos de referencia**

<br>

## **DAMA y TOGAF**
<br>

### [DAMA-DMBOK](pdfs/DAMA-DMBOK.pdf){target="_blank"}

### [Estándar TOGAF](pdfs/togaf-standard9.2.pdf){target="_blank"}

### [Glosario TOGAF](pdfs/TOGAF_GlosarioEspañol_OG.pdf){target="_blank"}

### [Diagramado TOGAF](pdfs/Data Architecture.pdf){target="_blank"}

<br>

## **BPM y Arquitectura Empresarial**

<br>

### [Definición de principios de arquitectura para arquitectura empresarial de la organización](pdfs/IBERO-Handbook_MR_1-43-52.pdf){target="_blank"}

### [Business Process Management](https://bpmnotebook.wordpress.com/modelos-operacionales/){target="_blank"}


### [Modelo de Arquitectura Organizacional para Empresas Medianas en México](pdfs/Arquitectura Empresarial - Victor Amezcua - Final para impresión1.pdf){target="_blank"}

### [Lineamientos para la AI](https://365inegi-my.sharepoint.com/:w:/r/personal/raul_mejia_inegi_org_mx/_layouts/15/Doc.aspx?sourcedoc=%7BB8C9B8BC-3A2A-4B2E-900D-4EDB7E69CB11%7D&file=Lineamientos_AI.docx&action=default&mobileredirect=true){target="_blank"}

<br>

## **UNECE**

<br>

### [GSBPM](https://statswiki.unece.org/display/GSBPM/Generic+Statistical+Business+Process+Model){target="_blank"}

### [GSBPM Finer level](https://statswiki.unece.org/display/GSBPM/Finer-level+of+Activities+of+Generic+Statistical+Business+Process+Model){target="_blank"} 


### [CSPA](https://statswiki.unece.org/display/CSPA/Common+Statistical+Production+Architecture){target="_blank"}

### [CSDA 2.0](https://statswiki.unece.org/display/DA/CSDA+2.0){target="_blank"}

### [GSIM 2.0 Wiki Clickable ](https://statswiki.unece.org/display/gsim){target="_blank"}

### [GSIM 2.0 Glosario](https://unece.github.io/GSIM-2.0/GSIMv2.html){target="_blank"}

### [GSIM 1.2 Glosario](https://statswiki.unece.org/display/gsim/GSIM+v1.2+Glossary){target="_blank"}

### [Linking GSBPM - GSIM](https://365inegi.sharepoint.com/sites/dgiai/100_DGG_DGIAII/150_DAA_DGAI/Documentos%20compartidos/SAI/Estrategia%20de%20arquitectura/Apoyo/Linking%20GSBPM%20-%20GSIM){target="_blank"}

### [Information flow within GSBPM using GSIM](https://statswiki.unece.org/display/GSBPM/Information+flow+within+GSBPM+using+GSIM){target="_blank"}

### [Mapping to GSIM Business Group](https://github.com/linked-statistics/COOS/issues/4){target="_blank"}

### [Information flow within GSBPM using GSIM](https://statswiki.unece.org/display/GSBPM/Information+flow+within+GSBPM+using+GSIM){target="_blank"}

### [Mapping GSIM - SDMX - DDI ](https://statswiki.unece.org/display/gsim/GSIM+and+standards){target="_blank"}

<br>

## **SDMX y DDI**

<br>

### [SDMX Documentation](https://sdmx.org/wp-content/uploads/SDMX_3-0-0_SECTION_2_FINAL-1_0.pdf){target="_blank"}

### [DDI Documentation](https://ddialliance.github.io/ddimodel-web/DDI-L-3.3/topics/All%20Content%20Items/){target="_blan"}

### [SDMX Project Management Guideline](https://statswiki.unece.org/display/SDMXPM/Checklist+for+SDMX+Design+Projects+Home){target="_blan"}

	


<br>
<br>


