---
title: "**Generales**"
--- 
<br>
<br>
<br>

<div class=text-justify>



# **Sitios**

<br>
 

### [Planner de la SAI](https://planner.cloud.microsoft/webui/plan/n6JyRDIj-kaIQN3Rg4w_GWQAEUbV/view/board?tid=ca8f09f5-335e-4fc5-8041-f5b472a02eef){target="_blank"} 

<br>

### [Sitio del CoAC](https://extranet.inegi.org.mx/calidad/){target="_blank"} 


<br>

### [One Drive Personal](https://365inegi-my.sharepoint.com/personal/raul_mejia_inegi_org_mx/_layouts/15/onedrive.aspx){target="_blank"} 


<br>

### [PAEG (SNIEG)](https://www.snieg.mx/paeg/){target="_blank"} 

<br>
<br>

# **Normas y documentos**

<br>

### [Reglamento Interior INEGI](pdfs/RIINEGI31725.pdf){target="_blank"} 

<br>

### [Estructura](pdfs/catalogo.pdf){target="_blank"}

<br>

### [Manual de Organización Específica de la DGIAI](pdfs/MOEDGIAI25.pdf){target="_blank"}
 
<br>

### [Manual de Procedimientos de la DGAII](pdfs/MP_15Oct21.pdf){target="_blank"}

<br>

### [NTPPIEG](https://sc.inegi.org.mx/repositorioNormateca/On_19Nov21.pdf){target="_blank"}

<br>

### [Inventario de Programas de Información](https://ptracking.snieg.mx/ipi/){target="_blank"}

<br>



### [Lineamientos de Coordinación Operativa](pdfs\Lod_15Jun21.pdf){target="_blank"}

<br> 


### Funciones SAI

DIRIGIR Y DECIDIR LA SUPERVISIÓN DE LAS ACTIVIDADES ESTADÍSTICAS Y GEOGRÁFICAS DE LA INFORMACIÓN DE INTERÉS NACIONAL Y/O INFORMACIÓN PÚBLICA OFICIAL, COORDINANDO AL PERSONAL A SU CARGO, LOS PROYECTOS ADMINISTRATIVOS Y TÉCNICOS DE SU ADSCRIPCIÓN EN MATERIA DE INFORMACIÓN ESTADÍSTICA, LA EJECUCIÓN Y DESARROLLO DE LAS FUNCIONES Y PROGRAMAS DE TRABAJO QUE CONTRIBUYEN AL CUMPLIMIENTO DE LOS PROGRAMAS Y OBJETIVOS INSTITUCIONALES, E INSTRUMENTACIÓN DE ACCIONES PREVISTAS EN CADA UNA DE LAS FASES QUE REGULA LA NORMA TÉCNICA DEL PROCESO DE PRODUCCIÓN DE INFORMACIÓN ESTADÍSTICA Y GEOGRÁFICA PARA EL INEGI, OBSERVANDO EL REGLAMENTO INTERIOR DEL INEGI, LOS MANUALES DE ORGANIZACIÓN ESPECÍFICOS, DE PROCEDIMIENTOS, LAS DISPOSICIONES LEGALES, NORMATIVAS Y LOS DERIVADOS DE LA LEGISLACIÓN VIGENTE EN MATERIA DE INFORMACIÓN ESTADÍSTICA Y GEOGRÁFICA, TRANSPARENCIA Y ACCESO A LA INFORMACIÓN PÚBLICA, Y EN MATERIA DE RESPONSABILIDADES ADMINISTRATIVAS DE LOS SERVIDORES PÚBLICOS. 

EJECUTAR LAS ACCIONES EN MATERIA DE ARQUITECTURA DE LA INFORMACIÓN PARA IMPULSAR LA ESTANDARIZACIÓN, EVALUACIÓN Y MEJORA DE LA MISMA; 

DECIDIR Y EFECTUAR LA IDENTIFICACIÓN DE NECESIDADES INSTITUCIONALES EN MATERIA DE ARQUITECTURA DE LA INFORMACIÓN PARA CONTRIBUIR AL DISEÑO DE LAS  PROPUESTAS DE POLÍTICAS, NORMAS Y PROCEDIMIENTOS; 

VIGILAR LAS ACTIVIDADES RELACIONADAS CON LA IMPLEMENTACIÓN DE POLÍTICAS, NORMAS Y PROCEDIMIENTOS EN MATERIA DE ARQUITECTURA DE LA INFORMACIÓN PARA MEJORAR SU GESTIÓN EN EL MARCO DEL PROCESO DE PRODUCCIÓN ESTADÍSTICO Y GEOGRÁFICO. 

DESARROLLAR LAS DEMÁS FUNCIONES QUE EN SU ÁMBITO DE COMPETENCIA Y NIVEL DE RESPONSABILIDAD, LE ENCOMIENDE SU JEFE INMEDIATO, OBSERVANDO PARA ESTA Y LAS DEMÁS FUNCIONES ANTES CITADAS, LOS PROCEDIMIENTOS DE SU ÁREA DE ADSCRIPCIÓN Y LAS DISPOSICIONES LEGALES, NORMATIVAS Y LOS DERIVADOS DE LA LEGISLACIÓN VIGENTE EN MATERIA DE INFORMACIÓN ESTADÍSTICA Y GEOGRÁFICA; TRANSPARENCIA Y ACCESO A LA INFORMACIÓN PÚBLICA, Y EN MATERIA DE RESPONSABILIDADES ADMINISTRATIVAS DE LOS SERVIDORES PÚBLICOS.



